apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: nginx
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
      protocol: TCP