apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - containerPort: 80
